# Generated by Django 5.0.2 on 2024-02-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=50)),
                ('gallery_image', models.FileField(default=None, max_length=250, null=True, upload_to='media/%y')),
            ],
        ),
    ]
