# Generated by Django 5.0.2 on 2024-03-24 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0001_initial'),
        ('report', '0002_remove_dentist_user_dentist_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='dentist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentist.dentist'),
        ),
        migrations.DeleteModel(
            name='Dentist',
        ),
    ]
