# Generated by Django 5.0.2 on 2024-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_patientreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient_email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
