# Generated by Django 5.0.2 on 2024-02-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0010_alter_appointment_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='am_pm',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2),
        ),
    ]
