# Generated by Django 5.0.2 on 2024-02-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0011_appointment_am_pm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='am_pm',
        ),
    ]
