# Generated by Django 5.0.2 on 2024-02-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0015_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
