# Generated by Django 5.0.2 on 2024-03-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0016_alter_appointment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Services',
            field=models.CharField(default='select service', max_length=45),
        ),
    ]
