# Generated by Django 5.0.1 on 2024-02-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_service_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
    ]
