# Generated by Django 5.0.2 on 2024-02-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_additional_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='service/'),
        ),
    ]
