# Generated by Django 5.0.2 on 2024-02-16 16:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='additional_details',
            field=tinymce.models.HTMLField(),
        ),
    ]
