# Generated by Django 5.0.2 on 2024-02-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_service_additional_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=50)),
                ('gallery_image', models.FileField(default=None, max_length=250, null=True, upload_to='media/%y')),
            ],
        ),
    ]
