# Generated by Django 5.0.2 on 2024-02-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
