# Generated by Django 5.0.2 on 2024-03-25 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0002_alter_dentist_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a valid 10-digit phone number.'), django.core.validators.MinValueValidator(0, message='Enter a valid 10-digit phone number.'), django.core.validators.MaxValueValidator(9999999999, message='Enter a valid 10-digit phone number.')]),
        ),
    ]
