# Generated by Django 5.0.2 on 2024-03-25 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0004_alter_dentist_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', 'Enter a valid 10-digit phone number.', 'invalid')]),
        ),
    ]
