# Generated by Django 5.0.2 on 2024-03-25 17:26

import dentist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentist', '0005_alter_dentist_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='contact_no',
            field=models.CharField(max_length=10, validators=[dentist.models.validate_contact_no]),
        ),
    ]
